language: en
# input_channel: custom_webhook

pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
- name: SpacyTokenizer
- name: SpacyEntityExtractor
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 2
- name: DIETClassifier
  epochs: 100
  learning_rate: 0.001

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100


















# language: en
# pipeline:
#   - name: WhitespaceTokenizer
#   - name: LanguageModelFeaturizer
#     model_name: "bert"
#     model_weights: "rasa/LaBSE"
#   - name: DIETClassifier
#     epochs: 100
#     learning_rate: 0.001
# policies:
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100

